## Why NumPy
Its Fast

Behind the scenes Optimizations written in c

Vectorization via broadcasting
 
Backbone of other Python scientific packages


## What are going to cover

Most useful funcations

Numpy datatypes & attributes(ndarray)

Creating arrays

Viewing arrays & matrices

Manipulating & comparing arrays

Sorting arrays

Use cases

In [2]:
#Import Numpy
import numpy as np

## DataTypes & Attributes

In [3]:
# Numpy's main datatype is ndarray
#1- D array
a1 = np.array([2,4,6,8])
a1

array([2, 4, 6, 8])

In [4]:
type(a1)

numpy.ndarray

In [5]:
#2-D array
a2 = np.array([[2.3,5.3,6.3],
             [4.6,2.3,9.0]])

#3-D array
a3 = np.array([[[1,3,4],
              [4,8,1],
              [4,9,4]],
              [[12,34,53],
              [48,99,88],
              [77,44,2]]])

In [6]:
a2

array([[2.3, 5.3, 6.3],
       [4.6, 2.3, 9. ]])

In [7]:
a3

array([[[ 1,  3,  4],
        [ 4,  8,  1],
        [ 4,  9,  4]],

       [[12, 34, 53],
        [48, 99, 88],
        [77, 44,  2]]])

In [8]:
#Attributes
a1.shape

(4,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
#show the all diminisonal 
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [12]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
a1.size,a2.size,a3.size

(4, 6, 18)

In [14]:
type(a1), type(a2), type(a3) 

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
#Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  2.3  5.3  6.3
1  4.6  2.3  9.0

## Create Array

In [16]:
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [17]:
simple_array.dtype

dtype('int64')

In [18]:
ones = np.ones((2,3))

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype, type(ones)

(dtype('float64'), numpy.ndarray)

In [21]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_arrya = np.random.randint(0,10,size=(3,5))
random_arrya

array([[6, 9, 5, 9, 3],
       [7, 3, 8, 9, 5],
       [9, 9, 7, 0, 2]], dtype=int32)

In [24]:
random_arrya.shape , random_arrya.size

((3, 5), 15)

In [25]:
random_array1 = np.random.random((2,3))
random_array1

array([[0.48561287, 0.90019405, 0.57212578],
       [0.79571849, 0.81585656, 0.72928701]])

In [26]:
random_array2 = np.random.rand(1,2,2,5)
random_array2

array([[[[2.62031063e-01, 3.24418385e-01, 8.69139810e-01,
          4.10665984e-01, 3.48937266e-01],
         [1.55983344e-04, 9.29880528e-01, 5.50160493e-01,
          4.50481721e-01, 4.85105375e-01]],

        [[5.80031113e-01, 3.53164640e-01, 8.99498054e-01,
          7.26418151e-01, 1.78093487e-01],
         [2.57743166e-01, 9.16306493e-01, 3.86156314e-01,
          3.88148819e-01, 6.71419382e-01]]]])

In [27]:
#Pseudo-random number
#np.random.seed()
random_array4 = np.random.randint(10,size=(5,3))
random_array4

array([[0, 6, 0],
       [7, 0, 4],
       [9, 3, 1],
       [0, 1, 4],
       [9, 0, 3]], dtype=int32)

In [28]:
random_array4

array([[0, 6, 0],
       [7, 0, 4],
       [9, 3, 1],
       [0, 1, 4],
       [9, 0, 3]], dtype=int32)

In [29]:
# We use seed fix the number using random
np.random.seed(seed=1)
random_array4 = np.random.randint(10,size=(5,3))
random_array4

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]], dtype=int32)

In [30]:
random_array4

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]], dtype=int32)

In [31]:
#seed = 0 when give random number the save u exextute with seed = 2 and reexute seed =0 same output comes
np.random.seed(seed=6)
random_array5 = np.random.randint(10,size=(5,3))
random_array5

array([[9, 3, 4],
       [0, 9, 1],
       [9, 1, 4],
       [1, 8, 2],
       [4, 2, 5]], dtype=int32)

## 3. Viewing arrays and matrices

In [33]:
np.unique(random_array5)

array([0, 1, 2, 3, 4, 5, 8, 9], dtype=int32)

In [34]:
a1

array([2, 4, 6, 8])

In [35]:
a2

array([[2.3, 5.3, 6.3],
       [4.6, 2.3, 9. ]])

In [36]:
a3

array([[[ 1,  3,  4],
        [ 4,  8,  1],
        [ 4,  9,  4]],

       [[12, 34, 53],
        [48, 99, 88],
        [77, 44,  2]]])

In [44]:
a1[0]

np.int64(2)

In [45]:
a2[0]

array([2.3, 5.3, 6.3])

In [49]:
a3[:2, :2, :2]

array([[[ 1,  3],
        [ 4,  8]],

       [[12, 34],
        [48, 99]]])

In [52]:
a4 = np.random.randint(10,size = (2, 3, 4, 5))
a4

array([[[[6, 3, 2, 1, 6],
         [8, 8, 9, 0, 7],
         [6, 0, 1, 8, 5],
         [9, 8, 5, 9, 1]],

        [[1, 2, 9, 9, 5],
         [6, 4, 0, 4, 2],
         [6, 2, 1, 9, 2],
         [0, 2, 2, 5, 0]],

        [[7, 6, 6, 0, 9],
         [5, 4, 8, 2, 4],
         [2, 3, 9, 4, 0],
         [5, 7, 6, 1, 1]]],


       [[[7, 1, 6, 8, 1],
         [5, 9, 2, 2, 4],
         [8, 7, 1, 5, 3],
         [4, 6, 4, 5, 6]],

        [[8, 5, 9, 7, 0],
         [3, 4, 6, 2, 7],
         [6, 0, 5, 8, 8],
         [8, 6, 1, 5, 2]],

        [[1, 7, 2, 7, 0],
         [5, 5, 8, 3, 4],
         [7, 9, 2, 6, 1],
         [2, 3, 3, 2, 1]]]], dtype=int32)

In [53]:
#Get the first 4 number of the inner most arrays 
a4[:, :, :, :1]

array([[[[6],
         [8],
         [6],
         [9]],

        [[1],
         [6],
         [6],
         [0]],

        [[7],
         [5],
         [2],
         [5]]],


       [[[7],
         [5],
         [8],
         [4]],

        [[8],
         [3],
         [6],
         [8]],

        [[1],
         [5],
         [7],
         [2]]]], dtype=int32)