## Why NumPy
Its Fast

Behind the scenes Optimizations written in c

Vectorization via broadcasting
 
Backbone of other Python scientific packages


## What are going to cover

Most useful funcations

Numpy datatypes & attributes(ndarray)

Creating arrays

Viewing arrays & matrices

Manipulating & comparing arrays

Sorting arrays

Use cases

In [1]:
#Import Numpy
import numpy as np

## DataTypes & Attributes

In [13]:
# Numpy's main datatype is ndarray
#1- D array
a1 = np.array([2,4,6,8])
a1

array([2, 4, 6, 8])

In [14]:
type(a1)

numpy.ndarray

In [23]:
#2-D array
a2 = np.array([[2.3,5.3,6.3],
             [4.6,2.3,9.0]])

#3-D array
a3 = np.array([[[1,3,4],
              [4,8,1],
              [4,9,4]],
              [[12,34,53],
              [48,99,88],
              [77,44,2]]])

In [24]:
a2

array([[2.3, 5.3, 6.3],
       [4.6, 2.3, 9. ]])

In [25]:
a3

array([[[ 1,  3,  4],
        [ 4,  8,  1],
        [ 4,  9,  4]],

       [[12, 34, 53],
        [48, 99, 88],
        [77, 44,  2]]])

In [18]:
#Attributes
a1.shape

(4,)

In [19]:
a2.shape

(2, 3)

In [26]:
a3.shape

(2, 3, 3)

In [28]:
#show the all diminisonal 
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [29]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [30]:
a1.size,a2.size,a3.size

(4, 6, 18)

In [31]:
type(a1), type(a2), type(a3) 

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [37]:
#Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  2.3  5.3  6.3
1  4.6  2.3  9.0

## Create Array

In [40]:
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [41]:
simple_array.dtype

dtype('int64')

In [49]:
ones = np.ones((2,3))

In [50]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [53]:
ones.dtype, type(ones)

(dtype('float64'), numpy.ndarray)

In [55]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [63]:
random_arrya = np.random.randint(0,10,size=(3,5))
random_arrya

array([[8, 3, 2, 9, 6],
       [2, 7, 3, 5, 1],
       [9, 4, 3, 0, 3]], dtype=int32)

In [64]:
random_arrya.shape , random_arrya.size

((3, 5), 15)

In [78]:
random_array1 = np.random.random((2,3))
random_array1

array([[0.83272328, 0.14581786, 0.34347974],
       [0.93074767, 0.02614892, 0.88901482]])

In [74]:
random_array2 = np.random.rand(1,2,2,5)
random_array2

array([[[[0.55799904, 0.46935314, 0.57803822, 0.10577048, 0.39603498],
         [0.74315491, 0.67010618, 0.39621019, 0.2875391 , 0.02072613]],

        [[0.65474115, 0.95008759, 0.87689782, 0.85543414, 0.77567797],
         [0.90592559, 0.3169187 , 0.03555345, 0.5956756 , 0.7664121 ]]]])

In [82]:
#Pseudo-random number
#np.random.seed()
random_array4 = np.random.randint(10,size=(5,3))
random_array4

array([[5, 3, 7],
       [6, 8, 0],
       [1, 8, 7],
       [4, 4, 3],
       [1, 3, 5]], dtype=int32)

In [83]:
random_array4

array([[5, 3, 7],
       [6, 8, 0],
       [1, 8, 7],
       [4, 4, 3],
       [1, 3, 5]], dtype=int32)

In [103]:
# We use seed fix the number using random
np.random.seed(seed=1)
random_array4 = np.random.randint(10,size=(5,3))
random_array4

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]], dtype=int32)

In [104]:
random_array4

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]], dtype=int32)

In [128]:
#seed = 0 when give random number the save u exextute with seed = 2 and reexute seed =0 same output comes
np.random.seed(seed=6)
random_array5 = np.random.randint(10,size=(5,3))
random_array5

array([[9, 3, 4],
       [0, 9, 1],
       [9, 1, 4],
       [1, 8, 2],
       [4, 2, 5]], dtype=int32)